(deftheme brian
  "Brian's custom theme")

(custom-theme-set-faces
 'brian
 '(cursor ((t (:background "#C8CCD5" :foreground "#101114"))))
 '(escape-glyph ((t (:foreground "#56B6C4"))))
 '(homoglyph ((t (:foreground "#56B6C4"))))
 '(minibuffer-prompt ((t (:foreground "#56B6C4"))))
 '(highlight ((t (:background "#E5C07C" :foreground "#101114"))))
 '(region ((t (:background "#C8CCD5" :foreground "#101114"))))
 '(shadow ((t (:foreground "#ABB1BF"))))
 '(secondary-selection ((t (:background "#545863"))))
 '(trailing-whitespace ((t (:background "#E06C75"))))
 '(font-lock-builtin-face ((t (:foreground "#E5C07C"))))
 '(font-lock-comment-delimiter-face ((t (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#56B6C4"))))
 '(font-lock-constant-face ((t (:foreground "#61AFEF" :weight bold))))
 '(font-lock-doc-face ((t (:inherit (font-lock-string-face)))))
 '(font-lock-function-name-face ((t (:foreground "#56B6C4" :weight bold))))
 '(font-lock-keyword-face ((t (:foreground "#E5C07C"))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:inherit (font-lock-builtin-face)))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#C877DD"))))
 '(font-lock-type-face ((t (:foreground "#99C37A"))))
 '(font-lock-variable-name-face ((t (:foreground "#E5C07C"))))
 '(font-lock-warning-face ((t (:inherit (error)))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:foreground "#56B6C4" :underline t))))
 '(link-visited ((t (:inherit link :foreground "#C877DD"))))
 '(fringe ((t (:background "#545863"))))
 '(header-line ((t (:inherit mode-line :background "#545863" :foreground "#C8CCD5" :box nil))))
 '(tooltip ((t (:inherit variable-pitch :background "#ABB1BF" :foreground "#101114"))))
 '(mode-line ((t (:box (:line-width -1 :style released-button) :foreground "#ABB1BF" :background "#545863"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t (:box (:line-width 2 :color "#545863" :style released-button)))))
 '(mode-line-inactive ((t (:weight light :box (:line-width -1 :color "grey40") :foreground "#C8CCD5" :background "#545863" :inherit mode-line))))
 '(isearch ((t (:background "#E5C07C" :foreground "#101114"))))
 '(isearch-fail ((t (:background "#E06C75" :foreground "#101114"))))
 '(lazy-highlight ((t (:background "#56B6C4" :foreground "#101114"))))
 '(match ((t (:background "#61AFEF" :foreground "#101114"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'brian)
